name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - uses: microsoft/setup-msbuild@v1

    - uses: actions/checkout@v3

    - name: Restore, Build and Publish
      run: |
        dotnet publish -c Release
                        
    - name: Generate release tag
      run: echo "release_tag=Release_$(date +"%Y.%m.%d_%H-%M")" >> $GITHUB_OUTPUT
    
    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: Release.zip
        path: D:/a/Greenshot/Greenshot/Greenshot/bin/Release/net7.0-windows/publish/*
        
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        files: |
          D:/a/Greenshot/Greenshot/Greenshot/bin/Release/net7.0-windows/publish/Release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
