name: Release

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - uses: microsoft/setup-msbuild@v1

    - uses: actions/checkout@v3

    - name: Restore, Build and Publish
      run: |
        dotnet publish -c Release -p:PublishDir=${{RUNNER_TEMP}}/publish
                        
    - name: Generate release tag
      id: tag
      run: |
        echo "release_tag=Release_$(date +"%Y.%m.%d_%H-%M")" >> $env:GITHUB_ENV

    - name: Zip Release
      uses: TheDoctor0/zip-release@0.7.1
      with:
        filename: Release.zip
        directory: ${{RUNNER_TEMP}}/publish
        
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: "${{ env.release_tag }}"
        files: |
          ${{RUNNER_TEMP}}/publish/Release.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
