name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Set the value
      id: step_one
      run: |
        echo "action_state=yellow" | Out-File -FilePath $env:GITHUB_ENV -Append # no need for -Encoding utf8

    - name: Set the value
      id: step_one_date
      run: |
        echo "release_tag=Release_$(date +"%Y.%m.%d_%H-%M")" | Out-File -FilePath $env:GITHUB_ENV -Append

    - name: Use the value
      id: step_two
      run: |
        echo "${{ env.action_state }}" # This will output 'yellow'

    - name: Use the value
      id: step_two_date
      run: |
        echo "${{ env.release_tag }}"
        
